### ISSUE TITLE
Set up business logic for differentiating between recruiter, applicant, and moderator

### ISSUE THREAD

**Issue by sulemanmalik** [scrum-gang/jobhub-web#3]
### Describe why the project needs this task
A recruiter has a different UI than an applicant who has a different UI from a moderator. In order for each user type to execute their specific functions, the business logic (and by extension the UI) needs to be different for each.

### Related user stories
* S2

### Describe the solution to the problem
Applicant - Should only be able to see available in-house job postings as well as the applicant dashboard.
Recruiter - Should only be able to see applications made as well as form for creating an in-house job posting.
Moderator - Should be able to see admin dashboard

**Comment by erickzhao** [comment]
Done internally to the best of our capabilities
